GET http://localhost:3000/

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username":"Jibin",
    "email":"jibin@jibin.com",
    "password":"pass" 
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username":"Sam",
    "email":"sam@sam.com",
    "password":"pass" 
}

###
POST http://localhost:3000/users/authenticate
Content-Type: application/json

{
    "email":"sam@sam.com",
    "password":"pass" 
}