GET http://localhost:3000/

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username":"Jibin",
    "email":"jibin@jibin.com",
    "password":"pass" 
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username":"Sam",
    "email":"sam@sam.com",
    "password":"pass" 
}

###
POST http://localhost:3000/users/authenticate
Content-Type: application/json

{
    "email":"sam@sam.com",
    "password":"pass" 
}

###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJTYW0iLCJlbWFpbCI6InNhbUBzYW0uY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkR1BMYm1yd21LTTNxZXJDZlM1U1NRZW94eENmLkdPZFZOeXNpL0xHc0guYm83bFVSSlRBcHUiLCJpYXQiOjE1OTQyMzY1NDR9.SMsVibqsBR_OO6P-H9TSwoIY3mFedSlaP0j-RQpIwNo